import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from '@Components/NavBar';
import Footer from '@Components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "B.N.U. Barber",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{display:"flex" , justifyContent: "center", alignItems: "center" , flexDirection:"column"}} >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
